apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-nonprd-uat
  namespace: argocd
spec:
  project: default
  source:
    path: ./
    repoURL: git@github.com:miw1513/k8s-calculator-nonprd.git
    targetRevision: main
    helm:
      releaseName: calculator-nonprd-uat
      valueFiles:
        - ./helm-values/uat.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: calculator-nonprd-uat
  syncPolicy:
    automated:
      prune: true