apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-config-nonprd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:expertep/k8s-calculator-config-nonprd.git
    targetRevision: main
    path: manifest/dev
  destination:
    server: https://34.142.138.192
    namespace: kev-dev
  syncPolicy:
    automated:
      prune: true