apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-nonprd-dev
  namespace: argocd
spec:
  project: default
  source:
    path: ./
    repoURL: git@github.com:expertep/k8s-calculator-nonprd.git
    targetRevision: main
    helm:
      releaseName: calculator-nonprd-dev
      valueFiles:
        - ./helm-values/dev.yaml
  destination:
    server: https://34.142.138.192
    namespace: kev-dev
  syncPolicy:
    automated:
      prune: true